### ISSUE TITLE
[FEATURE] Hybrid Requirement

### ISSUE THREAD

**Issue by HSGamer** [BetterGUI-MC/Issue-Tracker#9]
### Type

Plugin

### Specific

Requirement

### Content

I'm thinking of a new **Requirement Type** that combines multiple **Requirement Set** and adds more logic to them.

The logic includes:
- Minimum Requirement: The plugin would check if there are an amount of **Requirement Set** equal or higher than the minimum value.
- Success Only: If a set of **Requirement Set** are met, only successful ones will be executed. Otherwise, all sets are executed regardless of the success status.
- Optional Requirement: When a set of **Requirement Set** are met, If a set is marked as optional, its actions will not be executed.

The format would look like
```yaml
hybrid:
  success-only: <true/false>
  minimum: 1
  
  <requirement-set1>:
    requirement1: value1
    requirement2: value2
    requirement3: value3
    
    optional: <true/false>
  
  <requirement-set2>:
    requirement1: value1
    requirement2: value2
    requirement3: value3
    
    optional: <true/false>
  
  <requirement-set2>:
    requirement1: value1
    requirement2: value2
    requirement3: value3
    
    optional: <true/false>
```

### Screenshots & Links

A similar implementation on DeluxeMenus: https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations/requirements
